spring:
  application:
    name: Devourerhizine
  datasource:
    url: "jdbc:mysql://10.0.250.1:3306/devourerhizine?character_set_server=utf8mb4&useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=PRC"
    username: dev
    password: "ChongQing@MySQL3306"
    test-while-idle: true
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    validation-query: "select 1"
  redis:
    host: 10.0.250.1
    database: 0
rabbitmq:
  host: 10.0.250.1
  port: 5672
  user: guest
  password: guest
bill:
  defaultAuthenticationType: Signature
  keyOfHashCompareAuthenticationProviderClass: com.petroun.devourerhizine.classes.HashCompareAuthenticationKeyProvider
  keyOfHashCompareAuthenticationProviderMethod: key
  keyOfHashCompareAuthenticationXUValidateProviderMethod: uvalidate
  keyOfHashCompareAuthenticationPathPrefix: "/api/v1"
  allowDevSkipSignature: "YES"
  allowAuthDebuger: "YES"

gtconfig:
  url: "http://203.203.28.106:80/GtTripleGate/NoKeyInServlet"
  copartnerId: 60020021
  copartnerPassword: 123456

logging:
  path: logs

